networks:
  app_network:
    driver: bridge

volumes:
  portainer_data:
  sqlserver_data:
  activemq_data:
  seq_data:
  redis_data:

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    networks:
      - app_network
    ports:
      - "50000:9000"
      - "50001:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    networks:
      - app_network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=4dm1nP4ssw0rd@
    ports:
      - "50002:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    restart: always
    networks:
      - app_network
    ports:
      - "50003:61616"
      - "50004:8161"
    volumes:
      - activemq_data:/opt/activemq/data
    environment:
      - ACTIVEMQ_CONFIG_MAXINACTIVITYDURATION=30000
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    networks:
      - app_network
    ports:
      - "50005:80"
      - "50006:5341"
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=admin

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app_network
    ports:
      - "50007:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
