networks:
  app_network:
    driver: bridge

volumes:
  portainer_data:
  sqlserver_data:

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    networks:
      - app_network
    ports:
      - "50000:9000"
      - "50001:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    networks:
      - app_network
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=4dm1nP4ssw0rd@
    ports:
      - "50002:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
